--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    service: serviceapi
  name: serviceapi
spec: 
  type: NodePort
  ports:
  - name: "serviceapi"
    port: 5400
    targetPort: 80
    nodePort: 30002 
  selector: 
    service: serviceapi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: serviceapi
  name: serviceapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: serviceapi
    spec:
      containers:
      - image: training_synch_com_serviceapi
        name: serviceapi
        imagePullPolicy: IfNotPresent