version: "3.7"
services: 
  &MY_CONF
  webapp2:
    container_name: mywebappservice
    build:
      context: .
      dockerfile: WebApp2/Dockerfile           
      args:
        buildno: 1
    ports:
    - "8080-8082:80"
    image: mywebapp2:1
    deploy:
      mode: replicated
      replicas: 2